dotnet publish src\KcpNatProxy.ServerApp\KcpNatProxy.ServerApp.csproj -c Release -r win-x64 -o artifacts\win-x64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:AppEnableTraceLogging=true
dotnet publish src\KcpNatProxy.ServerApp\KcpNatProxy.ServerApp.csproj -c Release -r linux-x64 -o artifacts\linux-x64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:AppEnableTraceLogging=true
dotnet publish src\KcpNatProxy.ServerApp\KcpNatProxy.ServerApp.csproj -c Release -r win-arm64 -o artifacts\win-arm64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:AppEnableTraceLogging=true
dotnet publish src\KcpNatProxy.ServerApp\KcpNatProxy.ServerApp.csproj -c Release -r linux-arm64 -o artifacts\linux-arm64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true -p:AppEnableTraceLogging=true

dotnet publish src\KcpNatProxy.ClientApp\KcpNatProxy.ClientApp.csproj -c Release -r win-x64 -o artifacts\win-x64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:AppEnableTraceLogging=true
dotnet publish src\KcpNatProxy.ClientApp\KcpNatProxy.ClientApp.csproj -c Release -r linux-x64 -o artifacts\linux-x64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:AppEnableTraceLogging=true
dotnet publish src\KcpNatProxy.ClientApp\KcpNatProxy.ClientApp.csproj -c Release -r win-arm64 -o artifacts\win-arm64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:AppEnableTraceLogging=true
dotnet publish src\KcpNatProxy.ClientApp\KcpNatProxy.ClientApp.csproj -c Release -r linux-arm64 -o artifacts\linux-arm64 --self-contained=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:AppEnableTraceLogging=true
